app:
  name: "App API"
  version: "1.0.0"

postgres:
  username: !ENV ${POSTGRES_USER}
  password: !ENV ${POSTGRES_PASSWORD}
  host: "postgres"
  port: 5432
  dbname: !ENV ${POSTGRES_DB}
  echo: true  # SQLAlchemy echo logs
